# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global: {}

name: mq-spring-app

replicaCount: 1
logLevel: "info"

image:
  repository: replace
  tag: replace
  pullPolicy: IfNotPresent
  port: 8080

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

route:
  enabled: true

ingress:
  enabled: false
  appid:
    enabled: false
    # web or app - https://cloud.ibm.com/docs/services/appid?topic=appid-kube-auth
    requestType: web

#  host: hello
  namespaceInHost: true
  subdomain: containers.appdomain.cloud
  path: "/"

#  tlsSecretName: ""

jaegerConfigName: jaeger-config
jaegerSecretName: jaeger-access
jaegerCollectorEndpoint: http://jaeger-all-in-one-inmemory-collector.openshift-operators.svc.cluster.local:14268/api/traces

vcsInfo:
  repoUrl: ""
  branch: ""

partOf: inventory

connectsTo: ""

runtime: spring

configmap:
  CHANNEL: IBM.APP.SVRCONN
  CONNECTION_NAME: qm-dev-ibm-mq.dev.svc.cluster.local(1414)
  QM: QM1
  QUEUE_NAME: IBM.DEMO.Q
  APP_NAME: MQ-SPRING-APP

sealedsecret:
  PASSWORD: AgCaejI9kEilCgQFWtfQE8GgMvQqeQVexYh+toZjjo8PsT1gXcJkz0t9+8h+ShtuhLNPtLU+rI9yMZ0D0miemVeq0ZEwk6oeb6U/hQH5X+sUgdTRA22zT8jkCSrdFX/iqgoXfS8tWqpnibarpIWssDIPbMZMCYzk3XtIVz/aCqqmLjaEBCS/qqIa9mNUgr8ApnvYhdA+iONpLRJeHLC5qL7D3DQwsODL+VhmX6DcouahRNf2YwVo4luLA+2k9QXOh90U7I3+9LECjYhIUYOx2gpEQvl4DP0ORVuw+4P+pK9LbkaRpAPnUytf5QodGJGr8i79dUNVyxNYvhp6P3bJBt1QZaGJ5TFUKdObc+HpMJyPUgQPwldlhHJ22h4ddl6neCJbiZZCGmLgj+xLusqZ54DuNR0j65OQvVBXIeFYCfLNFbMnxod+KjuO5a6kgYCkvi+0wO9eT5FOWRm5U4xOv6OSqDGb1QV/FteEND/T3CersSWEF3OQ4vD2mMsHNlYaHZqFjB+5nOJNufdimawGAChSlRB1+pxL5GaPXjsgBWsEaIRDd8LJm3++pp4NJ5KE5AULAw5qUtDnvW+07T8wxpW4JDnwPSmxS0sP0GP6oJHMBHRR6j8ZpivgT5agOVMcnEqKAHVBHVzfPNqJQSJLaDmxh4WQFbr3gbxl2gfhhYmqeEFc7OCHMZN8GO19elpKdxVlPYw=
  USER: AgAMnfauPd8ID4WlFtkbAfRzGfuqDXzeYWLeOir0qylzFPvwSaoPdIAa3jEQhzv7NK+iQJg95iicYplcpw44r0/mH+pGFtAiaCL6X/FaSWjg+O6P2P1o1UGYVXnrhLpKjnVlHHHLri0E3ixC9s710AVLaDWiLZd98OAKIaDH0/G1UmkR6+Bt1UarLFJG0w04CGp85pOjTUicHfGIzZSnat/0lXrA9gXXeNuePJOj6tcb8NhVMecFYjGXKs9mg5F61VlBIgdZrJH/qWwuV4ta0IVRYhaWu66mXyo/PKXPVTrqMUCc9dViIOtcNV65QyCKIGIMrNOyQuf73Ve8BteLnDnW0X5WdaNC6sfGGG3VycLKP/xijOXOp9496Hsi6NvMY9B0Gvi/Ibdm/7gW0qaObsJO1JnTEa9VVJWm2/IuN89u9k0u48fGThWEDBTWJpZvDNHWXQWfqv2qIHzVbwPQFiOjQT03y4k2ZkerdWwKXw1+acndLYij/q71PKflTfYAlmnJ6UEN6gOj6k4idsJphgG0ot6Mv55qJChanl2q8IS/Wh7emfpt+uKNJ7X9jeF7CGI0DcYZTSjMvmKQ8ny3rT6PGWkB5L4CJi92oPunAnIIieST10HClwH0laRet3PYUyUaQhH83F29Vq+WyRCHEnep86+YGESiF7baNAoJHzBvUV2HtV16AlByryGWDFLV3QmgAJz43w==
  isScopeClusterWide: "true"

certs:
  volumeName: certs
  certSecretName: mq-client-jks
  certPasswordSecretName: mq-client-jks-password
  volumeMountPath: "/certs"
  trustStoreFileName: truststore.jks
  keyStoreFileName: keystore.jks

security: false

postSyncJob:
  enabled: false
